export enum ForumStatus {
  FUNCTIONAL_WITH_EMAIL = 'FUNCTIONAL_WITH_EMAIL',
  FUNCTIONAL_WITHOUT_EMAIL = 'FUNCTIONAL_WITHOUT_EMAIL',
  GUESTBOOK = 'GUESTBOOK',
  REGISTRATION_DENIED = 'REGISTRATION_DENIED',
  NOT_WORKING = 'NOT_WORKING',
  NO_FORUM = 'NO_FORUM',
  OTHER_ISSUE = 'OTHER_ISSUE'
}